### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Sea-Eagle** [manjitlatthe/ionic-php-ccavenue-integration#3]
I have followed as intructions but still it is not working.

Can you please provide sample demo app code which is given below of readme.md

**Comment by manjitlatthe** [comment]
Demo link is removed because ccavenue details has been changed. So you need to follow instructions properly. The given code is working properly. This code is used for https://play.google.com/store/apps/details?id=com.ionicframework.dmsmobile&hl=en this application. And it is working.
